name: Workflow for group 14

on:
  push:
    branches: ["main"]
    
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2 
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: | 
            ${{ runner.os }}-r-
      - name: Install R packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("DBI", "RSQLite", "ggplot2", "lubridate","readr"), dependencies = TRUE)'
      - name: Execute R script
        run: |
          Rscript Prep.R
        working-directory: DM_project
      - name: Configure Git
        run: |
          git config --global user.email "u5521398@live.warwick.ac.uk"
          git config --global user.name "AdnanAndar98"
        working-directory: DM_project
      - name: Commit updated database
        run: |
          git add e_commerce_database.db
          git commit -m "Update database with new data" || echo "No changes to commit"
        working-directory: DM_project
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.DM_TKN }}
          branch: main
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: main
