name: Workflow for group 14

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
  steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("tidyverse", "RSQLite", "DBI", "readxl"))'

      - name: Execute R Markdown script
        run: Rscript -e 'rmarkdown::render("Prep.Rmd")'
        working-directory: DM_project

      - name: Configure Git
        run: |
          git config --global user.email "u5521398@live.warwick.ac.uk"
          git config --global user.name "AdnanAndar98"
          working-directory: DM_project
          
      - name: Commit updated database
        run: |
          git add DM_project/e_commerce_database.db
          git commit -m "Update database with new data" || echo "No changes to commit"
          git push origin main
          working-directory: DM_project

      - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: main
      working-directory: DM_project

